# Generated by Django 5.1 on 2024-08-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_consumer_restaurant_rider_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='available',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='phone_number',
        ),
    ]
