# Generated by Django 5.1 on 2024-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='restaurant_location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
