# Generated by Django 5.1 on 2024-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_menucategory_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
