from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserViewSet, RestaurantViewSet, RiderViewSet, OrderViewSet, ConsumerViewSet,
    RegisterRestaurantView, RegisterRiderView, RegisterConsumerView, LoginView,
    MenuCategoryViewSet, MenuItemViewSet
)

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'restaurants', RestaurantViewSet)
router.register(r'riders', RiderViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'consumers', ConsumerViewSet)
router.register(r'categories', MenuCategoryViewSet)
router.register(r'items', MenuItemViewSet)

urlpatterns = [
    path('', include(router.urls)),  # Includes all routes generated by the DefaultRouter
    path('register/restaurant/', RegisterRestaurantView.as_view(), name='register_restaurant'),
    path('register/rider/', RegisterRiderView.as_view(), name='register_rider'),
    path('register/consumer/', RegisterConsumerView.as_view(), name='register_consumer'),
    path('login/', LoginView.as_view(), name='login'),
    path('api/categories/', MenuCategoryViewSet.as_view({'get': 'list'}), name='categories'),
    path('api/restaurants/', MenuCategoryViewSet.as_view({'get': 'list'}), name='categories'),
    path('api/items/', MenuItemViewSet.as_view({'get': 'list'}), name='items'),

]
